name: .NET Test 🚀

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version:
        - 9.0.x
        - 8.0.x
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Before Build
        shell: pwsh
        run: ./before_build.ps1

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Unit Tests
        shell: pwsh
        run: |
          dotnet test "./CloudinaryDotNet.Tests/CloudinaryDotNet.Tests.csproj" `
            --configuration Release `
            --no-build

      - name: Integration Tests
        shell: pwsh
        run: |
          dotnet test "./CloudinaryDotNet.IntegrationTests/CloudinaryDotNet.IntegrationTests.csproj" `
            --configuration Release `
            --no-build
